/* global window, document, Image, jQuery */
/* jshint devel:true */
/*!
 * Footbal Ticket Trade v0.0.1 (https://footbaltickettrade.com)
 * Project description
 *
 * by kuus <kunderikuus@gmail.com> (http://kunderikuus.net/)
 * Copyright (C) kunderi kuus, Inc - All Rights Reserved 2016-2017
 */
!function(e,o,n){"use strict";function i(e,o){var n,i=o||200;return function(){var o=this,t=arguments;clearTimeout(n),n=setTimeout(function(){e.apply(o,Array.prototype.slice.call(t))},i)}}function t(){n(".readmore").readmore({speed:180,moreLink:'<div class="readmore-toggle"><a href="#">Read more</a> <i class="icon icon-angle-down"></i></div>',lessLink:'<div class="readmore-toggle"><a href="#">Close</a> <i class="icon icon-angle-up"></i></div>',afterToggle:function(e,o,i){n(o).toggleClass("expanded",i)}})}function a(){var o=n("#modal-welcome"),i=n("#modal-welcome-btn-continue");!n.cookie("welcomeMobile")&&e.innerWidth<992&&(o.modal().on("shown.bs.modal",function(){n.cookie("welcomeMobile","1",{expires:365,path:"/"})}).on("hide.bs.modal",function(){}),i.click(function(){})),n(".modal-remote").click(function(e){var o=this,i=n(o.getAttribute("data-modal")),t=i.find(".modal-body");i.on("show.bs.modal",function(){t.load(o.href)}).modal(),e.preventDefault()})}function c(){n(".event-list-item").on("click",function(e){if(!n(e.target).is("a")){var i=n(this),t=i.find("a.btn")[0];t&&(o.location.href=t.href)}})}function s(){n(".tip").tooltip({container:"body"})}function r(){n(".box-header--title").fitText(2,{minFontSize:"14px",maxFontSize:"30px"})}function l(){var t=n(e),a=n("body"),c=e.innerWidth,s=t.scrollTop(),r=n("#why-book-with-us"),l=n("#about"),d=n(".header-top"),u=d.outerHeight(),f=n(".header-to-stick"),h=!1,m=!1,g=n("#col-tickets"),v=n("#col-stadium"),p=o.getElementById("stadium-img"),b=!1,k=n("#tickets-list"),w=n("#navbar").find(".dropdown-menu"),y=function(){f.addClass("sticky-header").clone().addClass("sticky-header-clone").insertAfter(f),h=!0},x=function(){s>=u&&c>=992&&!m&&(h||y(),a.addClass("sticky-header-on"),m=!0),(s<u&&m||c<992&&m)&&(a.removeClass("sticky-header-on"),m=!1)};c>=992&&y();var C=function(){c>=768&&c<992?l.css("min-height",r.outerHeight()):l.css("min-height",0)},T=function(){if(g.length&&v.length&&k.length)if(p&&p.src&&!b){var e=new Image;e.src=p.src,e.onload=H,b=!0}else H(),b=!0},H=function(){if(c>=992){var e=v.outerHeight(),o=e-90;k.css({"max-height":o})}else k.css({"max-height":"none"})},z=function(){c>=768?w.css({"max-height":e.innerHeight-f.outerHeight()-20,overflow:"auto"}):w.css({"max-height":"none",overflow:"auto"})};t.scroll(function(){s=t.scrollTop(),x()}),t.resize(function(){c=e.innerWidth,C(),x(),z()}),t.resize(i(function(){T()})),C(),T(),x(),z()}n(o).ready(function(){l(),r(),t(),a(),c(),s()})}(window,document,jQuery);